import type { GetServerSideProps, NextPage } from 'next'
import { getSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Posts from '../components/Posts'
import Sidebar from '../components/Sidebar'

type pageProps = {
  userid: string | undefined | null
  profilePic: string
  username: string
  expires: string
}

const Home = ({ userid, profilePic, username, expires }: pageProps) => {
  // console.log('EXPIRES', expires<Date.now()?"":"")

  return (
    <div>
      <Head>
        <title>Social Media App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='h-screen flex '>
        {/* SIDE BAR */}
        {/* <Sidebar username={username} /> */}
        {/* Post AREA */}
        <Posts logedInUser={userid} image={profilePic} username={username} />
        {/* Friends List */}
        {/* <div>FRIENDS LIST</div> */}
      </div>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context)

  if (!session) {
    return {
      props: {
        userid: null,
        profilePic: 'https://www.w3schools.com/howto/img_avatar.png',
        username: 'Beautiful person on the Internet',
      },
    }
  }
  // console.log(session)
  return {
    //@ts-ignore
    props: {
      //@ts-ignore
      userid: session?.user?.id,
      profilePic: session?.user?.image,
      //@ts-ignore
      username: session?.user?.username,
      expires: session?.expires,
    },
  }
}
